### ISSUE TITLE
Consolidation of the Model

### ISSUE THREAD

**Issue by kerkphil** [OpenSourcePolicyCenter/dynamic#3]
The individual pieces of the extended model need to be folded into a single document that lays out the model in its entirety.

**Comment by kerkphil** [comment]
I have consolidated all the notes on the dynamic model in a newly reformulated version of AEIBYUDyn.tex in the Github dynamic repository

This is how it was constructed.
Demographics from “Wealth Tax”, the current draft  of that paper
Household behavior from “Extended Consumers Problem”, added by Kerk 
Production firm behavior from “Simple Firms” and “Extended Firms Problem”, added by Jason and Kerk
Government from “Government_description” and “Fiscal Rule”, added by Jason and Kerk

We need to do the following:
Consolidate notation in the Production Goods Producers section.  Right now there are two alternative subsections one from Jason, one from Kerk.
Incorporate the optimal choice of bonds issued from Kerk's section into Jason's.
Add the optimal choice of equity stocks for the production firms.
Add a write up of the Consumption Goods Producers.
Consolidate notation in the Government section.

I've kept all the original individual documents, but I suggest we stop using them ASAP and do our editing on AEIBYUDyn.tex, which we can rename if needed.  Eventually we should clean out any old outdate documents in the repo.

**Comment by jdebacker** [comment]
Since a single document is going to be very long and get unwieldy quickly, I propose using modular documents that can then be complied separately - and later called into in a single latex document for the final product.  

How about the following tex files (just focusing on model description for now- leaving calibration and results for later):
- HH_description.tex
- Firm_description.tex
- Govt_description.tex
- Eqm_defn.tex
- Model_soln.tex

This pieces then can all then be included (unsing the /input or /include command) in the AEIBYUDyn.tex file that will compile the huge, final document.  Let me know if those divisions are ok with you and I'll get started moving pieces around.  

We desperately need a document to make sure we are using consistent notation across all parts of the model.  I'll get started on that today.

Note that we will still have some "notes" documents floating around that have some overlap with those model documents above.  This is necessary since those documents above will specify the full blown model pieces, but we'll need documents describing the simpler versions of models that  (e.g., I had created one supply side document with the full blown model and then added another yesterday with the description of the first and most simple version of that that we should add to the code).

**Comment by kerkphil** [comment]
I like this idea. I say start moving!

Sent from my iPhone

On Feb 22, 2015, at 7:15 AM, Jason DeBacker <notifications@github.com<mailto:notifications@github.com>> wrote:


Since a single document is going to be very long and get unwieldy quickly, I propose using modular documents that can then be complied separately - and later called into in a single latex document for the final product.

How about the following tex files (just focusing on model description for now- leaving calibration and results for later):

  *   HH_description.tex
  *   Firm_description.tex
  *   Govt_description.tex
  *   Eqm_defn.tex
  *   Model_soln.tex

This pieces then can all then be included (unsing the /input or /include command) in the AEIBYUDyn.tex file that will compile the huge, final document. Let me know if those divisions are ok with you and I'll get started moving pieces around.

We desperately need a document to make sure we are using consistent notation across all parts of the model. I'll get started on that today.

Note that we will still have some "notes" documents floating around that have some overlap with those model documents above. This is necessary since those documents above will specify the full blown model pieces, but we'll need documents describing the simpler versions of models that (e.g., I had created one supply side document with the full blown model and then added another yesterday with the description of the first and most simple version of that that we should add to the code).

-

**Comment by jdebacker** [comment]
Notation guide is up.  Note that there is an excel file and a tex document.  The tex documents creates tables from the excel file.  Right now, both should be updated when there are changes/additions- the excel file is nice to carry around because it also contains notes and information on the calibration of parameters, and indentifying equations for variables, etc.

**Comment by jdebacker** [comment]
Master document - AEIBYUDyn.tex created such that it pulls from the following .tex files (which are now chapters in the main document):

1) Household_description
2) Firms_description
3) Government_description
4) Eqn_description
5) Model_soln

Everything Kerk had in the file before is there (except some overlap where I replaced his more detailed firm with the even more detailed firm stuff from August - but his equations are still in the repo in another document).  We'll easily be able to include sections for calibartion, etc in this master document.  I think this should help use manage the pieces better it does a nice job creating a TOC and so forth.
