### ISSUE TITLE
Check that resource constraint is satisfied in the SS.py and TPI.py solution

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/dynamic#70]
@evan-magnusson Can you check that C+I=Y (where I=delta*K in the SS) from the solution to SS.py (i.e., using Kss, Yss, cssmat, and omega_SS).  I did this and didn't find the constraint satisfied, but I may have done something wrong.

**Comment by evan-magnusson** [comment]
@jdebacker In the original tested folder, or in the new SS.py files that we made this week to add the firms?

**Comment by jdebacker** [comment]
@evan-magnusson Sorry - in the TESTED_DONT_TOUCH folder.

**Comment by evan-magnusson** [comment]
All of the problems with the resource constraint have now been found.  Pending @rickecon finalizing the theory on how to put in the immigration rates, here is a checklist of things I will be doing to update the code (in the firmproblem folder).
[] Add g_n as an input to the get_K and get_BQ functions
[] put g_n_ss into parameter vector (and update all functions that unpack this) so that it isn't a global
[] put g_n vector into TPI calls of get_K and get_BQ
[] separate omega from lambda (this will involve adding inputs to a few functions)
[] use the stationarized resource constraint in TPI, SSgraphs and TPIgraphs
[] shift the immigration rates: make the last one 0
[] make the last survival rate 0 inside of demographics
[] output rho from demographics, don't compute it in run_simulation
[] test SS and TPI to make sure resource constraint is satisfied
[] copy all changed code to the wealth_tax repo in the SSmethod2 folder, except the run_simulation.py that does tax experiments

**Comment by evan-magnusson** [comment]
All of the items in the above checklist have been completed, with the exception of finding where in demographics.py the immigration rates are coded incorrectly.  The easy band-aid to this is to make immigration rates zero.  This will allow us to move forward and implement the firm side of the problem and merge these updated files with TJ's code.  Issue #87 will track our solving of the immigration rates problem from now on.
